name: qrapp
description: A Steven Smith Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_speed_dial: ^6.0.0
  json_annotation: ^4.5.0
  qr_code_scanner: ^0.7.0
  qr_flutter: ^4.0.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  test: ^1.21.1

flutter:
  uses-material-design: true
